const fs = require('node:fs');
const path = require('node:path');
const {
    lang, consonantLangs, vowelLetterLangs, meyEzuthuLangs,
    languageDetails, getRecordingKey, getAudioFilename, getRecordedAudioFilename, getRecordingVowel,
} = require('../src/letters');

const audioRoot = path.resolve(__dirname, '../audio');
const manifestPath = path.resolve(__dirname, '../src/audio-manifest.js');

function parseRecording(filename, language) {
    const match = filename.match(/^(.+) plus (.+)\. (.+)\.mp3$/u);
    if (!match) throw new Error(`Unrecognized recording filename: ${filename}`);
    const prefix = match[1].normalize('NFC');
    const virama = meyEzuthuLangs[language];
    const consonant = virama && prefix.endsWith(virama) ? prefix.slice(0, -virama.length) : prefix;
    return { consonant, vowel: match[2].normalize('NFC') };
}

function buildCatalog(root = audioRoot) {
    return lang.map((languageName, language) => {
        const directory = path.join(root, languageName);
        if (!fs.existsSync(directory)) return {};
        const preferred = new Map();
        consonantLangs[language].forEach((consonant, c) => {
            vowelLetterLangs[language].forEach((_, v) => {
                const component = getRecordingVowel(language, v);
                preferred.set(getRecordingKey(consonant, component), getAudioFilename(language, c, v));
            });
        });
        const candidates = new Map();
        for (const filename of fs.readdirSync(directory).filter(file => file.endsWith('.mp3')).sort()) {
            const { consonant, vowel } = parseRecording(filename, language);
            const key = getRecordingKey(consonant, vowel);
            if (!candidates.has(key)) candidates.set(key, []);
            candidates.get(key).push(filename);
        }
        return Object.fromEntries([...candidates].map(([key, files]) => {
            const exact = files.find(file => file === preferred.get(key));
            if (files.length > 1 && !exact) {
                throw new Error(`Ambiguous recordings for ${languageName} ${key}: ${files.join(', ')}`);
            }
            return [key, exact || files[0]];
        }));
    });
}

function serializeCatalog(catalog) {
    return '// Generated by npm run audio:map. Do not edit by hand.\n' +
        `var audioRecordings = ${JSON.stringify(catalog, null, 2)};\n\n` +
        "if (typeof module !== 'undefined' && module.exports) module.exports = audioRecordings;\n";
}

function mapAudio(check = false) {
    const catalog = buildCatalog();
    const content = serializeCatalog(catalog);
    if (check) {
        if (!fs.existsSync(manifestPath) || fs.readFileSync(manifestPath, 'utf8') !== content) {
            throw new Error('Audio manifest is out of date. Run npm run audio:map.');
        }
    } else {
        fs.writeFileSync(manifestPath, content);
    }
    let indexed = 0;
    lang.forEach((_, language) => {
        const count = Object.keys(catalog[language]).length;
        indexed += count;
        let mapped = 0;
        consonantLangs[language].forEach((_, consonant) => {
            vowelLetterLangs[language].forEach((_, vowel) => {
                if (getRecordedAudioFilename(language, consonant, vowel, catalog)) mapped++;
            });
        });
        const total = consonantLangs[language].length * vowelLetterLangs[language].length;
        console.log(`${languageDetails[language].code}: ${count} recordings; ${mapped}/${total} selections mapped.`);
    });
    console.log(`${indexed} recordings indexed. Manifest ${check ? 'verified' : 'written'}.`);
}

if (require.main === module) mapAudio(process.argv.includes('--check'));

module.exports = { buildCatalog, parseRecording, serializeCatalog, mapAudio };
